CREATE TABLE IF NOT EXISTS kit (
	id INTEGER PRIMARY KEY
	, deposit_in INTEGER NOT NULL DEFAULT 0
	, deposit_out INTEGER NOT NULL DEFAULT 0
	, handed_out INTEGER NOT NULL DEFAULT 0
	, handed_in INTEGER NOT NULL DEFAULT 0
	, ready_current INTEGER NOT NULL DEFAULT 0
	, ready_next INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS note (
	id INTEGER PRIMARY KEY
	, kit_id INTEGER NOT NULL
	, body TEXT NOT NULL
	, ok INTEGER NOT NULL DEFAULT 0
	, timestamp DATE
);
